name: theta-client upload xcframework on release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Build
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: podPublishXCFramework
      - name: zip
        run: |
          cd kotlin-multiplatform/build/cocoapods/publish/release
          zip -ry THETAClient.xcframework.zip THETAClient.xcframework
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./kotlin-multiplatform/build/cocoapods/publish/release/THETAClient.xcframework.zip
          asset_name: THETAClient.xcframework.zip
          asset_content_type: application/zip
